spring:
  datasource:
    url: jdbc:mysql://118.126.92.128:3306/financial?user=financial&password=financial&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  jpa:
    show-sql: true


server:
  context-path: /manager
  port: 8081 
  
swagger:
  groupName: manger
  basePackage: com.whoiszxl.manager.controller